pub const ForthError = error{
    TooManyEntries,
    NotFound,
    OverFlow,
    UnderFlow,
    BadOperation,
    WordReadError,
    ParseError,
    ParseStringError,
    ParseCommentError,
    ParseNumberError,
    ParseQuotedError,
    FormatError,
    OutOfMemory,
    AlreadyCompiling,
    NotCompiling,
    EOF,
};
